blank_issues_enabled: true
contact_links:
  - name: Original tldraw
    url: https://github.com/tldraw/tldraw-v1/issues/new
    about: Is your issue for the original tldraw? Report it on the original tldraw repo instead.
